# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import localflavor.us.models
import sh_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True)),
                ('description', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=260)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('date_created', models.TimeField(default=django.utils.timezone.now)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SH_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=260)),
                ('is_accepted', models.BooleanField(default=False)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvoted_on', to='sh_app.SH_User')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='sh_app.League')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='sh_app.SH_User')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_on', to='sh_app.SH_User')),
                ('voting_ends', models.DateTimeField(default=sh_app.models.set_default_vote_end_time, validators=[sh_app.models.validate_vote_time])),
                ('voting_starts', models.DateTimeField(default=django.utils.timezone.now, validators=[sh_app.models.validate_vote_time])),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='head_official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HOfficial_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='LM_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='league',
            name='officials',
            field=models.ManyToManyField(related_name='Official_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='attendants',
            field=models.ManyToManyField(related_name='attending', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='experts',
            field=models.ManyToManyField(related_name='expert_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huddles', to='sh_app.League'),
        ),
        migrations.RemoveField(
            model_name='huddle',
            name='time',
        ),
        migrations.RemoveField(
            model_name='league',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='huddle',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='huddle',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelOptions(
            name='sh_user',
            options={'verbose_name': 'SH_User', 'verbose_name_plural': 'SH_Users'},
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='league',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sh_user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sh_user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
