# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True)),
                ('description', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=260)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('date_created', models.TimeField(default=django.utils.timezone.now)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SH_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=260)),
                ('isAccepted', models.BooleanField(default=False)),
                ('votingstarts', models.TimeField()),
                ('votingends', models.TimeField()),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvoted_on', to='sh_app.SH_User')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='sh_app.League')),
                ('suggestedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='sh_app.SH_User')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_on', to='sh_app.SH_User')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='head_official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HOfficial_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='LM_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='league',
            name='officials',
            field=models.ManyToManyField(related_name='Official_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='attendants',
            field=models.ManyToManyField(related_name='attending', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='experts',
            field=models.ManyToManyField(related_name='expert_of', to='sh_app.SH_User'),
        ),
        migrations.AddField(
            model_name='huddle',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huddles', to='sh_app.League'),
        ),
    ]
