# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestedby',
            new_name='suggested_by',
        ),
        migrations.RemoveField(
            model_name='huddle',
            name='time',
        ),
        migrations.RemoveField(
            model_name='league',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='votingends',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='votingstarts',
        ),
        migrations.AlterField(
            model_name='huddle',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
