# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0001_squashed_0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='voting_starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
