# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sh_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0002_auto_20160429_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='huddle',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='voting_ends',
            field=models.DateTimeField(default=sh_app.models.set_default_vote_end_time, validators=sh_app.models.validate_vote_end),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='voting_starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
