# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0002_auto_20160502_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
