# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0003_suggestion_is_achieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='is_achieved',
            new_name='is_archived',
        ),
    ]
