# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import sh_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0003_auto_20160429_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sh_user',
            options={'verbose_name': 'SH_User', 'verbose_name_plural': 'SH_Users'},
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='isAccepted',
            new_name='is_accepted',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='voting_ends',
            field=models.DateTimeField(default=sh_app.models.set_default_vote_end_time, validators=[sh_app.models.validate_vote_end]),
        ),
    ]
