# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0004_auto_20160429_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sh_user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sh_user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
