# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sh_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0005_auto_20160429_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='voting_ends',
            field=models.DateTimeField(default=sh_app.models.set_default_vote_end_time, validators=[sh_app.models.validate_vote_time]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='voting_starts',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[sh_app.models.validate_vote_time]),
        ),
    ]
